---
ansible_connection: httpapi
ansible_network_os: eos
ansible_user: cvaas
ansible_password: PASTE-IN-ANSIBLE-SERVICE-TOKEN-FROM-CVAAS-HERE
ansible_become: yes
ansible_become_method: enable
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: true
ansible_python_interpreter: $(which python3)
