---
- name: Update Configlets and Devices
  hosts: cvaas
  connection: local
  gather_facts: no

  collections:
    - arista.cvp
    - arista.avd

  tasks:

    # Task will update Device configlet list and which container the device is connected
    - name: "Updating Devices Configlets and Parent Container"
      tags: [ update, device, full ]
      cv_device_v3:
        devices: "{{ CVP_DEVICES }}"
        state: present
      register: CVP_DEVICES_RESULT

    # Reminder message just in case there are Tasks that need to be executed in CVP
    # We do not automatically execute any tasks in CVP
    - name: "Follow Up Message"
      tags: [ always ]
      debug:
        msg: "If needed, manually create change control & execute any pending tasks in CVP to apply changes"

