---
- name: Update Configlets and Devices
  hosts: cvaas
  connection: local
  gather_facts: no

  collections:
    - arista.cvp
    - arista.avd

  tasks:

    # Task will update Device configlet list and which container the device is connected
    - name: "Updating Devices Configlets and Parent Container"
      tags: [ update, device, full ]
      cv_device_v3:
        devices: "{{ CVP_DEVICES }}"
        state: present
      register: CVP_DEVICES_RESULT

    # Automatically execute tasks from above task when assigned configlets
    - name: Execute all tasks registered in cvp_configlets variable
      tags: [execute]
      cv_task_v3:
        tasks: "{{ CVP_DEVICES_RESULT.taskIds }}"